CREATE DATABASE KEEPSAKE;
GO

USE KEEPSAKE;
GO

CREATE TABLE PATIENT_INFORMATION (
    PT_ID INT IDENTITY(1000,1) PRIMARY KEY,
    PT_LNAME VARCHAR(30) NOT NULL,
    PT_FNAME VARCHAR(20) NOT NULL,
    PT_MNAME VARCHAR(20) NULL,
    DT_OF_BIRTH DATE NOT NULL,
    MT_NAME VARCHAR(60) NULL,
    FT_NAME VARCHAR(60) NULL,
    CON_NUM VARCHAR(60) NULL,
    EMAIL_ADD VARCHAR(60) NULL,
	PT_FULLNAME AS PT_LNAME + ' ' + PT_LNAME,
	ISACTIVE BIT DEFAULT 1 NOT NULL
);


CREATE TABLE DOCTOR (
    DR_ID INT NOT NULL PRIMARY KEY,
    DR_NAME VARCHAR(60) NOT NULL,
    DEPPT VARCHAR(60) NOT NULL,
    SPLTY VARCHAR(30) NOT NULL,
    CONTACT VARCHAR(15) NULL
);

CREATE TABLE ACCOUNTS (
    USER_ID INT IDENTITY(1,1) PRIMARY KEY,
    USERTYPE BIT NOT NULL,
    PASSWORD VARCHAR(15) NOT NULL,
    EMP_ID CHAR(15) NULL,
    USER_LNAME VARCHAR(60) NOT NULL,
    USER_FNAME VARCHAR(60) NOT NULL
);

CREATE TABLE PRESCRIPTIONS (
    RX_ID INT IDENTITY(1,1) PRIMARY KEY,
    CU_TYPE TINYINT NOT NULL,
    [DATE] DATE NOT NULL,
    AGE INT NOT NULL,
    FINDINGS NVARCHAR(MAX) NOT NULL,
    CONSULT NVARCHAR(MAX) NULL,
    DR_INS NVARCHAR(MAX) NOT NULL,
    RETURN_DT DATE NULL,
    PT_ID INT REFERENCES PATIENT_INFORMATION(PT_ID),
    DR_ID INT REFERENCES DOCTOR(DR_ID)
);

CREATE TABLE ATPMC_MSRMT (
    AM_ID INT IDENTITY(1,1) PRIMARY KEY,
    WEIGHT FLOAT NOT NULL,
    LENGTH FLOAT NOT NULL,
    HEAD_CC FLOAT NOT NULL,
    CHEST_CC FLOAT NOT NULL,
    ABDML_GT FLOAT NOT NULL,
    PT_ID INT REFERENCES PATIENT_INFORMATION(PT_ID),
    RX_ID INT REFERENCES PRESCRIPTIONS(RX_ID)
);

CREATE TABLE SCREENING_TEST (
    ST_ID INT IDENTITY(1,1) PRIMARY KEY,
    ENS_DATE DATE NOT NULL,
    ENS_REMARKS BIT NOT NULL,
    NHS_DATE DATE NOT NULL,
    NHS_REAR BIT NOT NULL,
    NHS_LEAR BIT NOT NULL,
    POS_CCHD_DATE DATE NULL,
    POS_CCHD_RHAND BIT NOT NULL,
    POS_CCHD_LHAND BIT NOT NULL,
    ROR_DATE DATE NULL,
    ROR_REMARKS VARCHAR(60) NULL,
    PT_ID INT REFERENCES PATIENT_INFORMATION(PT_ID)
);

CREATE TABLE IMMUNIZATION_RECORD (
    VAX_ID INT IDENTITY(1,1) PRIMARY KEY,
    VAX VARCHAR(60) NOT NULL,
    DOSAGE FLOAT NOT NULL,
    [DATE] DATE NOT NULL,
    REMARKS NVARCHAR(MAX) NULL,
    PT_ID INT REFERENCES PATIENT_INFORMATION(PT_ID),
    DR_ID INT REFERENCES DOCTOR(DR_ID)
);

CREATE TABLE PATIENT_IMMUNIZATION (
    PI_ID INT IDENTITY(1,1) PRIMARY KEY,
    PT_ID INT REFERENCES PATIENT_INFORMATION(PT_ID),
    VAX_ID INT REFERENCES IMMUNIZATION_RECORD(VAX_ID)
);


INSERT INTO IMMUNIZATION_RECORD (VAX, DOSAGE, [DATE], REMARKS)
VALUES ('FLU VACCINE', 30, '10-22-2024', 'PATIENT IN GOOD CONDITION');

INSERT INTO PATIENT_IMMUNIZATION (PT_ID, VAX_ID)
VALUES (1000, 1);
	

-- TRIGGERS
-- TRIGGER FOR PATIENT_INFORMATION
CREATE TRIGGER TRG_PATIENT_INFO_INSERT_UPDATE
ON PATIENT_INFORMATION
AFTER INSERT, UPDATE
AS
BEGIN
    PRINT 'A RECORD WAS INSERTED OR UPDATED IN THE PATIENT_INFORMATION TABLE.'
    
END;

-- TRIGGER FOR DOCTOR
CREATE TRIGGER TRG_DOCTOR_INSERT_UPDATE
ON DOCTOR
AFTER INSERT, UPDATE
AS
BEGIN
    PRINT 'A RECORD WAS INSERTED OR UPDATED IN THE DOCTOR TABLE.'
    
END;

-- TRIGGER FOR PRESCRIPTIONS
CREATE TRIGGER TRG_PRESCRIPTIONS_INSERT_UPDATE
ON PRESCRIPTIONS
AFTER INSERT, UPDATE
AS
BEGIN
    PRINT 'A RECORD WAS INSERTED OR UPDATED IN THE PRESCRIPTIONS TABLE.'
    
END;

-- TRIGGER FOR IMMUNIZATION_RECORD
CREATE TRIGGER TRG_IMMUNIZATION_INSERT_UPDATE
ON IMMUNIZATION_RECORD
AFTER INSERT, UPDATE
AS
BEGIN
    PRINT 'A RECORD WAS INSERTED OR UPDATED IN THE IMMUNIZATION_RECORD TABLE.'
    
END;